CATEGORY_CONST_MAPPING = {
    'C__CATS__APPLICATION': "application",
    'C__CATG__IT_SERVICE': "it_service",
    'C__CATG__VERSION': 'version',
    'C__CATG__RELATION': 'relation',
    'C__CATG__PLANNING': 'planning',
    'C__CATG__GLOBAL': 'global',
    'C__CATG__CONTACT': 'contact',
    'C__CATG__APPLICATION': 'software_assignment',
    'C__CATS__APPLICATION_ASSIGNED_OBJ': 'application_assigned_obj',
    'C__CATS__APPLICATION_VARIANT': 'application_variant',
    'C__CATG__CLUSTER_SERVICE': 'cluster_service',
    'C__CATG__BACKUP': 'backup',
    'C__CATG__CLUSTER_MEMBERSHIPS': 'cluster_memberships',
    'C__CATG__POWER_CONSUMER': 'power_consumer',
    'C__CATG__NETWORK_PORT': 'network_port',
    'C__CATG__LOCATION': 'location',
    'C__CATG__UNIVERSAL_INTERFACE': 'universal_interface',
    'C__CATG__IP': 'ip',
    'C__CATG__CONTROLLER_FC_PORT': 'controller_fc_port',
    'C__CATG__CONNECTOR': 'connector',
    'C__CATG__LDEV_CLIENT': 'ldev_client',
    'C__CATG__GROUP_MEMBERSHIPS': 'group_memberships',
    'C__CATS__PERSON_ASSIGNED_GROUPS': 'person_assigned_groups',
    'C__CATS__DATABASE_ACCESS': 'database_access',
    'C__CATS__DATABASE_LINKS': 'database_links',
    'C__CATS__DATABASE_GATEWAY': 'database_gateway',
    'C__CATS__DATABASE_SCHEMA': 'database_schema',
    'C__CATG__IT_SERVICE_COMPONENTS': 'it_service_components',
    'C__CATS__REPLICATION_PARTNER': 'replication_partner',
    'C__CATG__SOA_COMPONENTS': 'soa_components',
    'C__CATG__SOA_STACKS': 'soa_stacks',
    'C__CATS__DATABASE_INSTANCE': 'database_instance',
    'C__CATG__ASSIGNED_CARDS': 'assigned_cards',
    'C__CATS__PERSON': 'person',
    'C__CATG__LOGICAL_UNIT': 'logical_unit',
    'C__CATS__ORGANIZATION': 'organization',
    'C__CATG__CONTRACT_ASSIGNMENT': 'contract_assignment',
    'C__CATS__CHASSIS_DEVICES': 'chassis_devices',
    'C__CATG__STACKING': 'stacking',
    'C__CATG__SHARE_ACCESS': 'share_access',
    'C__CATG__NAGIOS_REFS_SERVICES': 'nagios_refs_services',
    'C__CATG__NET_CONNECTOR': 'net_connector',
    'C__CATG__CLUSTER_ADM_SERVICE': 'cluster_adm_service',
    'C__CATG__OPERATING_SYSTEM': 'operating_system',
    'C__CATG__QINQ_SP': 'qinq_sp',
    'C__CATG__RM_CONTROLLER': 'rm_controller',
    'C__CATG__FILE': 'file',
    'C__CATG__VRRP': 'virtual_host',
    'C__CATG__MANUAL': 'vrrp',
    'C__CATG__EMERGENCY_PLAN': 'manual'
}

LOG_LEVEL_DEBUG = 10
LOG_LEVEL_INFO = 20
LOG_LEVEL_ERROR = 30
LOG_LEVEL_WARNING = 40

